import{Room,type Client}from"@colyseus/core";import{RoomStateSchema,PlayerStateSchema,RoundScoreSchema,WeaponAmmoStateSchema,type RoomStateSchemaInstance,PLAYER_NETWORK_INPUT_LIMITS as PIL,EVENTS,MatchPhase,BUILD_EVENTS,ENERGY_EVENTS,computeEnergyAfterRegeneration,applyStructureDamage,isStructureDestroyed,type WeaponState,type WeaponId,isWeaponId}from"@buildshift/protocol";import{stepPlayerMovement,movementInputToWorld,fireGate,hitscan,computePelletDirections,rayIntersectsCapsule}from"@buildshift/simulation";import{PLAYER_MOVEMENT,VERTICAL_MOVEMENT,ASSAULT_RIFLE,SHOTGUN,MAX_HEALTH,MAX_SHIELD,ROUNDS_TO_WIN,ROUND_COUNTDOWN_SECONDS as RCS,ROUND_RESET_DELAY_SECONDS as RRS,getStructureConfig,ENERGY,ENERGY_SHOTGUN}from"@buildshift/game-config";import{BuildingStateSchema,oc,wc}from"../state/buildingState.js";import{ServerPhysicsWorld}from"../physics/serverPhysicsWorld.js";import{MATCH_EVENTS}from"../match/matchLifecycle.js";import{handleBuildPlacement}from"../match/buildPlacement.js";
export const TWO_PLAYER_MOVEMENT_ROOM="two-player-movement";export const TWO_PLAYER_MOVEMENT_INPUT="two-player:input";export const WEAPON_SWITCH_INPUT="two-player:weapon_switch";export const RELOAD_INPUT="two-player:reload";
const THZ=30,TD=1/THZ;const MC={moveSpeed:PLAYER_MOVEMENT.moveSpeed,gravity:VERTICAL_MOVEMENT.gravity,jumpVelocity:VERTICAL_MOVEMENT.jumpVelocity,terminalVelocity:VERTICAL_MOVEMENT.terminalVelocity,groundY:VERTICAL_MOVEMENT.groundY};const W=ASSAULT_RIFLE,WID=W.id,EH=VERTICAL_MOVEMENT.playerHalfHeight,TR=0.4;const CT=Math.max(1,Math.round(RCS*THZ)),RT=Math.max(1,Math.round(RRS*THZ));const SP=[{x:-5,y:VERTICAL_MOVEMENT.groundY,z:0},{x:5,y:VERTICAL_MOVEMENT.groundY,z:0}];const CWO:WeaponId="assault_rifle";const WSE="combat:weapon_state";const LOADOUT:readonly WeaponId[]=["assault_rifle","shotgun"];const TMS=1000/THZ;
interface PWS{equippedWeaponId:WeaponId;magazineAmmo:number;reserveAmmo:number;reloading:boolean;reloadProgress:number;fireCooldownRemaining:number;}
function cws():PWS{return{equippedWeaponId:CWO,magazineAmmo:ASSAULT_RIFLE.maxAmmo,reserveAmmo:ASSAULT_RIFLE.maxReserve,reloading:false,reloadProgress:0,fireCooldownRemaining:0};}
function tws(ws:PWS):WeaponState{return{weaponId:ws.equippedWeaponId,ammoInMag:ws.magazineAmmo,ammoReserve:ws.reserveAmmo,reloading:ws.reloading,reloadRemainingMs:ws.reloadProgress};}
function cl(v:number,a:number,b:number){return v<a?a:v>b?b:v;}
function nm(x:unknown,a:number,b:number){return typeof x==="number"&&Number.isFinite(x)?cl(x,a,b):0;}
function ad(y:number,p:number){const c=Math.cos(p);return{x:Math.sin(y)*c,y:Math.sin(p),z:-Math.cos(y)*c};}
function pi(m:unknown){if(!m||typeof m!=="object")return null;const r=m as Record<string,unknown>,s=r.sequence;if(typeof s!=="number"||!Number.isFinite(s))return null;return{sequence:s,moveX:nm(r.moveX,PIL.movementMin,PIL.movementMax),moveZ:nm(r.moveZ,PIL.movementMin,PIL.movementMax),lookYaw:nm(r.lookYaw,-Math.PI,Math.PI),lookPitch:nm(r.lookPitch,PIL.pitchMin,PIL.pitchMax),jump:r.jump===true,primaryFire:r.primaryFire===true};}
type PE=InstanceType<typeof PlayerStateSchema>;
function rfall(d:number,fs:number,fe:number){if(d<=fs)return 1;if(d>=fe)return 0;return 1-(d-fs)/(fe-fs);}
export class TwoPlayerMovementRoom extends Room<{state:RoomStateSchemaInstance}>{
state=new RoomStateSchema();maxPlayers=2;
private readonly bld=new BuildingStateSchema();private readonly occ=new Set<string>();private readonly lpt=new Map<string,number>();
private tc=0;private sc=0;private pw:ServerPhysicsWorld|null=null;private readonly pwp:Promise<ServerPhysicsWorld>;
private readonly inb=new Map<string,any>();private jc=0;private readonly ss=new Map<string,number>();private ptl=0;
private readonly wps=new Map<string,PWS>();private readonly rt=new Map<string,ReturnType<typeof setTimeout>>();
constructor(...args:ConstructorParameters<typeof Room>){super(...args);(this.state as unknown as Record<string,unknown>).building=this.bld;this.pwp=ServerPhysicsWorld.create().then(w=>{this.pw=w;return w;});}
onCreate():void{this.onMessage(TWO_PLAYER_MOVEMENT_INPUT,(c,m)=>{this.hi(c,m);});this.onMessage(WEAPON_SWITCH_INPUT,(c,m)=>{this.hws(c,m);});this.onMessage(RELOAD_INPUT,(c,m)=>{this.handleReload(c,m);});this.onMessage(BUILD_EVENTS.PLACEMENT_REQUEST,(c,m)=>{this.hpr(c,m);});this.state.matchPhase=MatchPhase.COUNTDOWN;this.state.currentRound=0;this.ptl=CT;this.setFixedTimestep(()=>this.tick(),THZ);}
onJoin(c:Client):void{const si=this.jc%SP.length,sp=SP[si];this.jc++;this.ss.set(c.sessionId,si);const p=new PlayerStateSchema();p.x=sp.x;p.y=sp.y;p.z=sp.z;p.yaw=0;p.velocityY=0;p.grounded=true;p.lastProcessedSequence=-1;p.health=MAX_HEALTH;p.shield=MAX_SHIELD;p.energy=ENERGY.startingEnergy;p.ammo=W.maxAmmo;p.lastFireSequence=-1;p.alive=true;p.isEliminated=false;p.currentWeapon=CWO;this.wps.set(c.sessionId,cws());const ams=new WeaponAmmoStateSchema();ams.magazineAmmo=ASSAULT_RIFLE.maxAmmo;ams.reserveAmmo=ASSAULT_RIFLE.maxReserve;ams.isReloading=false;ams.reloadProgress=0;p.weapons.set(ASSAULT_RIFLE.id,ams);const sms=new WeaponAmmoStateSchema();sms.magazineAmmo=SHOTGUN.maxAmmo;sms.reserveAmmo=SHOTGUN.maxReserve;sms.isReloading=false;sms.reloadProgress=0;p.weapons.set(SHOTGUN.id,sms);this.state.players.set(c.sessionId,p);const r=new RoundScoreSchema();r.value=0;this.state.roundScore.set(c.sessionId,r);if(this.state.matchPhase===MatchPhase.MATCH_ENDED)this.rst();}
onLeave(c:Client,_e?:number):void{const ph=this.state.matchPhase as MatchPhase;if(ph===MatchPhase.IN_PROGRESS){const op=this.op(c.sessionId);if(op)this.er(op,c.sessionId);}const t=this.rt.get(c.sessionId);if(t){clearTimeout(t);this.rt.delete(c.sessionId);}this.state.players.delete(c.sessionId);this.inb.delete(c.sessionId);this.ss.delete(c.sessionId);this.lpt.delete(c.sessionId);this.wps.delete(c.sessionId);}
onDispose():void{this.inb.clear();this.ss.clear();this.lpt.clear();this.occ.clear();this.wps.clear();for(const[,t]of this.rt)clearTimeout(t);this.rt.clear();if(this.pw){this.pw.dispose();this.pw=null;}}
private op(sid:string):string|null{for(const k of this.state.players.keys())if(k!==sid)return k;return null;}
private hi(c:Client,m:unknown):void{const i=pi(m);if(!i)return;this.inb.set(c.sessionId,i);}
private async hpr(c:Client,msg:unknown):Promise<void>{this.sc++;await handleBuildPlacement(c,msg,{state:this.state,bld:this.bld,occ:this.occ,lpt:this.lpt,tc:this.tc,structureId:this.roomId+"-"+this.sc,pwPromise:this.pwp,broadcast:(ev,d)=>this.broadcast(ev,d),sendTo:(cl2,ev,d)=>cl2.send(ev,d)});}
private hws(c:Client,m:unknown):void{const ws=this.wps.get(c.sessionId);if(!ws)return;const p=this.state.players.get(c.sessionId);if(!p)return;if(!m||typeof m!=="object")return;const r=m as Record<string,unknown>;const t=r.targetWeaponId??r.weaponId;if(typeof t!=="string"||!isWeaponId(t))return;if(!LOADOUT.includes(t))return;ws.equippedWeaponId=t;ws.fireCooldownRemaining=0;p.currentWeapon=t;c.send(WSE,tws(ws));}
private handleReload(c:Client,_m:unknown):void{const sid=c.sessionId,ws=this.wps.get(sid);if(!ws)return;const mSz=ws.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.magazineCapacity:W.maxAmmo;const rMs=ws.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.reloadDurationMs:Math.round(W.reloadTicks*(1000/THZ));if(ws.magazineAmmo>=mSz)return;if(ws.reserveAmmo<=0)return;if(ws.reloading)return;ws.reloading=true;ws.reloadProgress=0;const t=setTimeout(()=>{const c2=this.wps.get(sid);if(!c2)return;const cSz=c2.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.magazineCapacity:W.maxAmmo;const cRs=c2.equippedWeaponId==="shotgun"?SHOTGUN.maxReserve:W.maxReserve;const a=Math.min(cSz-c2.magazineAmmo,c2.reserveAmmo);c2.magazineAmmo=Math.min(c2.magazineAmmo+a,cSz);c2.reserveAmmo=Math.max(0,c2.reserveAmmo-a);c2.reserveAmmo=Math.min(c2.reserveAmmo,cRs);c2.reloading=false;c2.reloadProgress=1;this.rt.delete(sid);const cl2=this.clients.find(x=>x.sessionId===sid);if(cl2)cl2.send(WSE,tws(c2));},rMs);this.rt.set(sid,t);}
private handleFire(sid:string,p:PE,yaw:number,pitch:number):void{