import{Room,type Client}from"@colyseus/core";import{RoomStateSchema,PlayerStateSchema,RoundScoreSchema,WeaponAmmoStateSchema,type RoomStateSchemaInstance,PLAYER_NETWORK_INPUT_LIMITS as PIL,EVENTS,MatchPhase,BUILD_EVENTS,computeEnergyAfterRegeneration,type WeaponState,type WeaponId,isWeaponId}from"@buildshift/protocol";import{stepPlayerMovement,movementInputToWorld,hitscan,computePelletDirections,rayIntersectsCapsule}from"@buildshift/simulation";import{PLAYER_MOVEMENT,VERTICAL_MOVEMENT,ASSAULT_RIFLE,SHOTGUN,MAX_HEALTH,MAX_SHIELD,ROUNDS_TO_WIN,ROUND_COUNTDOWN_SECONDS as RCS,ROUND_RESET_DELAY_SECONDS as RRS,ENERGY,ENERGY_SHOTGUN}from"@buildshift/game-config";import{BuildingStateSchema}from"../state/buildingState.js";import{ServerPhysicsWorld}from"../physics/serverPhysicsWorld.js";import{MATCH_EVENTS}from"../match/matchLifecycle.js";import{handleBuildPlacement}from"../match/buildPlacement.js";
export const TWO_PLAYER_MOVEMENT_ROOM="two-player-movement";
export const TWO_PLAYER_MOVEMENT_INPUT="two-player:input";
export const WEAPON_SWITCH_INPUT="two-player:weapon_switch";
export const RELOAD_INPUT="two-player:reload";
const THZ=30,TD=1/THZ;
const MC={moveSpeed:PLAYER_MOVEMENT.moveSpeed,gravity:VERTICAL_MOVEMENT.gravity,jumpVelocity:VERTICAL_MOVEMENT.jumpVelocity,terminalVelocity:VERTICAL_MOVEMENT.terminalVelocity,groundY:VERTICAL_MOVEMENT.groundY};
const W=ASSAULT_RIFLE,TR=0.4,CT=Math.max(1,Math.round(RCS*THZ)),RT=Math.max(1,Math.round(RRS*THZ)),SP=[{x:-5,y:VERTICAL_MOVEMENT.groundY,z:0},{x:5,y:VERTICAL_MOVEMENT.groundY,z:0}],CWO:WeaponId="assault_rifle",WSE="combat:weapon_state",LOADOUT:readonly WeaponId[]=["assault_rifle","shotgun"],TMS=1000/THZ;
interface PWS{equippedWeaponId:WeaponId;magazineAmmo:number;reserveAmmo:number;reloading:boolean;reloadProgress:number;fireCooldownRemaining:number;}
const cws=():PWS=>({equippedWeaponId:CWO,magazineAmmo:ASSAULT_RIFLE.maxAmmo,reserveAmmo:ASSAULT_RIFLE.maxReserve,reloading:false,reloadProgress:0,fireCooldownRemaining:0});
const tws=(ws:PWS):WeaponState=>({weaponId:ws.equippedWeaponId,ammoInMag:ws.magazineAmmo,ammoReserve:ws.reserveAmmo,reloading:ws.reloading,reloadRemainingMs:ws.reloadProgress});
const cl=(v:number,a:number,b:number)=>v<a?a:v>b?b:v;
const nm=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)?cl(x,a,b):0;
const ad=(y:number,p:number)=>{const c=Math.cos(p);return{x:Math.sin(y)*c,y:Math.sin(p),z:-Math.cos(y)*c};};
const pi=(m:unknown)=>{if(!m||typeof m!=="object")return null;const r=m as Record<string,unknown>,s=r.sequence;if(typeof s!=="number"||!Number.isFinite(s))return null;return{sequence:s,moveX:nm(r.moveX,PIL.movementMin,PIL.movementMax),moveZ:nm(r.moveZ,PIL.movementMin,PIL.movementMax),lookYaw:nm(r.lookYaw,-Math.PI,Math.PI),lookPitch:nm(r.lookPitch,PIL.pitchMin,PIL.pitchMax),jump:r.jump===true,primaryFire:r.primaryFire===true};};
type PE=InstanceType<typeof PlayerStateSchema>;
const rfall=(d:number,fs:number,fe:number)=>d<=fs?1:d>=fe?0:1-(d-fs)/(fe-fs);
export class TwoPlayerMovementRoom extends Room<{state:RoomStateSchemaInstance}>{
state=new RoomStateSchema();maxPlayers=2;private bld=new BuildingStateSchema();private occ=new Set<string>();private lpt=new Map<string,number>();private tc=0;private sc=0;private pw:ServerPhysicsWorld|null=null;private pwp:Promise<ServerPhysicsWorld>;private inb=new Map<string,any>();private jc=0;private ss=new Map<string,number>();private ptl=0;private wps=new Map<string,PWS>();private rt=new Map<string,ReturnType<typeof setTimeout>>();private rdl=0;
constructor(...args:ConstructorParameters<typeof Room>){super(...args);(this.state as unknown as Record<string,unknown>).building=this.bld;this.pwp=ServerPhysicsWorld.create().then(w=>{this.pw=w;return w;});}
onCreate(){this.onMessage(TWO_PLAYER_MOVEMENT_INPUT,(c,m)=>this.hi(c,m));this.onMessage(WEAPON_SWITCH_INPUT,(c,m)=>this.hws(c,m));this.onMessage(RELOAD_INPUT,(c)=>this.handleReload(c));this.onMessage(BUILD_EVENTS.PLACEMENT_REQUEST,(c,m)=>this.hpr(c,m));this.state.matchPhase=MatchPhase.COUNTDOWN;this.state.currentRound=0;this.ptl=CT;this.setFixedTimestep(()=>this.tick(),THZ);}
onJoin(c:Client){const si=this.jc%SP.length,sp=SP[si];this.jc++;this.ss.set(c.sessionId,si);const p=new PlayerStateSchema();p.x=sp.x;p.y=sp.y;p.z=sp.z;p.yaw=0;p.velocityY=0;p.grounded=true;p.lastProcessedSequence=-1;p.health=MAX_HEALTH;p.shield=MAX_SHIELD;p.energy=ENERGY.startingEnergy;p.ammo=W.maxAmmo;p.lastFireSequence=-1;p.alive=true;p.isEliminated=false;p.currentWeapon=CWO;this.wps.set(c.sessionId,cws());const a=new WeaponAmmoStateSchema();a.magazineAmmo=ASSAULT_RIFLE.maxAmmo;a.reserveAmmo=ASSAULT_RIFLE.maxReserve;a.isReloading=false;a.reloadProgress=0;p.weapons.set(ASSAULT_RIFLE.id,a);const s=new WeaponAmmoStateSchema();s.magazineAmmo=SHOTGUN.maxAmmo;s.reserveAmmo=SHOTGUN.maxReserve;s.isReloading=false;s.reloadProgress=0;p.weapons.set(SHOTGUN.id,s);this.state.players.set(c.sessionId,p);const r=new RoundScoreSchema();r.value=0;this.state.roundScore.set(c.sessionId,r);if(this.state.matchPhase===MatchPhase.MATCH_ENDED)this.rst();}
onLeave(c:Client){const ph=this.state.matchPhase as MatchPhase;if(ph===MatchPhase.IN_PROGRESS){const o=this.op(c.sessionId);if(o)this.er(o,c.sessionId);}const t=this.rt.get(c.sessionId);if(t){clearTimeout(t);this.rt.delete(c.sessionId);}this.state.players.delete(c.sessionId);this.inb.delete(c.sessionId);this.ss.delete(c.sessionId);this.lpt.delete(c.sessionId);this.wps.delete(c.sessionId);}
onDispose(){this.inb.clear();this.ss.clear();this.lpt.clear();this.occ.clear();this.wps.clear();for(const[,t]of this.rt)clearTimeout(t);this.rt.clear();if(this.pw){this.pw.dispose();this.pw=null;}}
private op(sid:string):string|null{for(const k of this.state.players.keys())if(k!==sid)return k;return null;}
private hi(c:Client,m:unknown){const i=pi(m);if(i)this.inb.set(c.sessionId,i);}
private async hpr(c:Client,msg:unknown):Promise<void>{this.sc++;await handleBuildPlacement(c,msg,{state:this.state,bld:this.bld,occ:this.occ,lpt:this.lpt,tc:this.tc,structureId:this.roomId+"-"+this.sc,pwPromise:this.pwp,broadcast:(ev,d)=>this.broadcast(ev,d),sendTo:(cl2,ev,d)=>cl2.send(ev,d)});}
private hws(c:Client,m:unknown){const ws=this.wps.get(c.sessionId);if(!ws)return;const p=this.state.players.get(c.sessionId);if(!p||!m||typeof m!=="object")return;const r=m as Record<string,unknown>,t=r.targetWeaponId??r.weaponId;if(typeof t!=="string"||!isWeaponId(t)||!LOADOUT.includes(t))return;ws.equippedWeaponId=t;ws.fireCooldownRemaining=0;p.currentWeapon=t;c.send(WSE,tws(ws));}
private handleReload(c:Client){const sid=c.sessionId,ws=this.wps.get(sid);if(!ws)return;const mS=ws.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.magazineCapacity:W.maxAmmo,rM=ws.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.reloadDurationMs:Math.round(W.reloadTicks*(1000/THZ));if(ws.magazineAmmo>=mS||ws.reserveAmmo<=0||ws.reloading)return;ws.reloading=true;ws.reloadProgress=0;const p=this.state.players.get(sid);if(p){const wa=p.weapons.get(ws.equippedWeaponId);if(wa){wa.isReloading=true;wa.reloadProgress=0;}}const t=setTimeout(()=>{const c2=this.wps.get(sid);if(!c2)return;const cS=c2.equippedWeaponId==="shotgun"?ENERGY_SHOTGUN.magazineCapacity:W.maxAmmo,cR=c2.equippedWeaponId==="shotgun"?SHOTGUN.maxReserve:W.maxReserve,a=Math.min(cS-c2.magazineAmmo,c2.reserveAmmo);c2.magazineAmmo=Math.min(c2.magazineAmmo+a,cS);c2.reserveAmmo=Math.max(0,Math.min(c2.reserveAmmo-a,cR));c2.reloading=false;c2.reloadProgress=1;this.rt.delete(sid);const cl2=this.clients.find(x=>x.sessionId===sid);if(cl2)cl2.send(WSE,tws(c2));const p2=this.state.players.get(sid);if(p2){const wa=p2.weapons.get(c2.equippedWeaponId);if(wa){wa.magazineAmmo=c2.magazineAmmo;wa.reserveAmmo=c2.reserveAmmo;wa.isReloading=false;wa.reloadProgress=1;}}},rM);this.rt.set(sid,t);}
private handleFire(sid:string,p:PE,yaw:number,pitch:number){const ws=this.wps.get(sid);if(!ws)return;const opp=this.op(sid);if(!opp)return;const op=this.state.players.get(opp);if(!op)return;if(ws.fireCooldownRemaining>0){this.broadcast(EVENTS.FIRE_REJECTED,{shooterId:sid,reason:"cooldown"});return;}if(ws.reloading){this.broadcast(EVENTS.FIRE_REJECTED,{shooterId:sid,reason:"reloading"});return;}const dir=ad(yaw,pitch);let td=0,hp={x:p.x,y:p.y,z:p.z};if(ws.equippedWeaponId==="shotgun"){const pl2=computePelletDirections(dir,ENERGY_SHOTGUN.pelletCount,ENERGY_SHOTGUN.spreadAngleDeg),o={x:p.x,y:p.y,z:p.z},tg={x:op.x,y:op.y,z:op.z},mx=ENERGY_SHOTGUN.rangeFalloffEnd;for(let i=0;i<pl2.length;i++){const pd=pl2[i],dl=Math.sqrt(pd.x*pd.x+pd.y*pd.y+pd.z*pd.z);if(dl<1e-12)continue;const rs=rayIntersectsCapsule(o,pd,tg,TR,mx);if(rs.hit){td+=ENERGY_SHOTGUN.perPelletDamage*rfall(rs.distance,ENERGY_SHOTGUN.rangeFalloffStart,ENERGY_SHOTGUN.rangeFalloffEnd);const tt=rs.distance/dl;hp={x:o.x+pd.x*tt,y:o.y+pd.y*tt,z:o.z+pd.z*tt};}}}else{const hs=hitscan({x:p.x,y:p.y,z:p.z},dir,{damage:W.damage,range:W.range},[{id:opp,position:{x:op.x,y:op.y,z:op.z}}]);if(hs.length>0){td=hs[0].damage;hp=hs[0].hitPoint;}}if(td>0){let rm=td;if(op.shield>0){const ab=Math.min(op.shield,rm);op.shield-=ab;rm-=ab;}if(rm>0)op.health=Math.max(0,op.health-rm);this.broadcast(EVENTS.HIT,{shooterId:sid,targetId:opp,damage:td,hitPoint:hp,weaponId:ws.equippedWeaponId});this.broadcast(EVENTS.HEALTH_UPDATE,{playerId:opp,health:op.health,shield:op.shield,alive:op.health>0,isEliminated:op.health<=0});if(op.health<=0){op.alive=false;op.isEliminated=true;this.broadcast(EVENTS.ELIMINATED,{eliminatedId:opp,eliminatedById:sid});this.er(sid,opp);}}if(ws.magazineAmmo>0){ws.magazineAmmo--;p.ammo=ws.magazineAmmo;const wa=p.weapons.get(ws.equippedWeaponId);if(wa)wa.magazineAmmo=ws.magazineAmmo;}ws.fireCooldownRemaining=ws.equippedWeaponId==="shotgun"?SHOTGUN.fireCooldownMs:W.fireCooldownMs;const inp=this.inb.get(sid);if(inp)p.lastFireSequence=inp.sequence;}
private tick(){this.tc++;const ph=this.state.matchPhase as MatchPhase;if(ph===MatchPhase.COUNTDOWN){this.ptl--;this.broadcast(MATCH_EVENTS.COUNTDOWN_TICK,{countdownTicks:this.ptl,totalTicks:CT});if(this.ptl<=0){this.state.matchPhase=MatchPhase.IN_PROGRESS;this.state.currentRound++;this.inb.clear();}
return;}if(ph===MatchPhase.ROUND_ENDED){this.rdl--;if(this.rdl<=0)this.rst();return;}if(ph!==MatchPhase.IN_PROGRESS)return;for(const[sid,p]of this.state.players){const ws=this.wps.get(sid);if(ws&&ws.fireCooldownRemaining>0)ws.fireCooldownRemaining=Math.max(0,ws.fireCooldownRemaining-TMS);p.energy=computeEnergyAfterRegeneration(p.energy,ENERGY.maxEnergy,1,ENERGY.regenPerTick);const inp=this.inb.get(sid);let mx=0,mz=0,jm=false;const seqValid=inp!==undefined&&inp!==null&&inp.sequence>p.lastProcessedSequence;if(seqValid){mx=inp.moveX;mz=inp.moveZ;jm=inp.jump;p.yaw=inp.lookYaw;p.lastProcessedSequence=inp.sequence;if(inp.primaryFire)this.handleFire(sid,p,inp.lookYaw,inp.lookPitch);}const wd=movementInputToWorld({x:mx,z:mz},p.yaw),res=stepPlayerMovement({x:p.x,y:p.y,z:p.z,vx:0,vy:p.velocityY,vz:0,onGround:p.grounded},{moveX:wd.x,moveZ:wd.z,jump:jm},TD,MC);p.x=res.x;p.y=res.y;p.z=res.z;p.velocityY=res.vy;p.grounded=res.onGround;}}
private er(winner:string,loser:string){const ws=this.state.roundScore.get(winner);if(ws)ws.value++;this.state.lastRoundResult.winnerId=winner;this.state.lastRoundResult.roundNumber=this.state.currentRound;const loserS=this.state.roundScore.get(loser);const loserScore=loserS?loserS.value:0;const winnerScore=ws?ws.value:0;this.state.matchPhase=MatchPhase.ROUND_ENDED;this.rdl=RT;this.broadcast(MATCH_EVENTS.ROUND_OVER,{winnerId:winner,loserId:loser,winnerScore,loserScore,roundNumber:this.state.currentRound});if(winnerScore>=ROUNDS_TO_WIN){this.state.matchPhase=MatchPhase.MATCH_ENDED;const scores:Record<string,number>={};for(const[k,v]of this.state.roundScore)scores[k]=v.value;this.broadcast(MATCH_EVENTS.MATCH_END,{winnerId:winner,scores});}}
private rst(){for(const[sid,p]of this.state.players){const si=this.ss.get(sid),sp=si!==undefined?SP[si]:SP[0];p.x=sp.x;p.y=sp.y;p.z=sp.z;p.yaw=0;p.velocityY=0;p.grounded=true;p.lastProcessedSequence=-1;p.health=MAX_HEALTH;p.shield=MAX_SHIELD;p.energy=ENERGY.startingEnergy;p.ammo=W.maxAmmo;p.lastFireSequence=-1;p.alive=true;p.isEliminated=false;p.currentWeapon=CWO;const ws=this.wps.get(sid);if(ws){ws.equippedWeaponId=CWO;ws.magazineAmmo=ASSAULT_RIFLE.maxAmmo;ws.reserveAmmo=ASSAULT_RIFLE.maxReserve;ws.reloading=false;ws.reloadProgress=0;ws.fireCooldownRemaining=0;}const aw=p.weapons.get(ASSAULT_RIFLE.id);if(aw){aw.magazineAmmo=ASSAULT_RIFLE.maxAmmo;aw.reserveAmmo=ASSAULT_RIFLE.maxReserve;aw.isReloading=false;aw.reloadProgress=0;}const sw=p.weapons.get(SHOTGUN.id);if(sw){sw.magazineAmmo=SHOTGUN.maxAmmo;sw.reserveAmmo=SHOTGUN.maxReserve;sw.isReloading=false;sw.reloadProgress=0;}}
}
